parameters:
#    lracicot_xmms2_php_remote.example.class: lracicot\Xmms2PHPRemoteBundle\Example

services:
#    lracicot_xmms2_php_remote.example:
#        class: %lracicot_xmms2_php_remote.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
